## Classifying Grayscale Images

The problem we’re trying to solve here is to classify grayscale images of handwritten digits (28 × 28 pixels) into their 10 categories (0 through 9). We’ll use the MNIST dataset, a classic in the machine learning community, which has been around almost as long as the field itself and has been intensively studied. It’s a set of 60,000 training images, plus 10,000 test images, assembled by the National Institute of Standards and Technology (the NIST in MNIST) in the 1980s.

In [1]:
from tensorflow.keras.datasets import mnist

(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

11490434/11490434 [==============================] - 0s 0us/step


In [2]:
train_images.shape

(60000, 28, 28)

In [3]:
len(train_labels)

60000

In [4]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [5]:
test_images.shape

(10000, 28, 28)

In [6]:
from tensorflow import keras
from tensorflow.keras import layers

model = keras.Sequential([
    layers.Dense(512, activation="relu"),
    layers.Dense(10, activation="softmax")
])

In [7]:
model.compile(optimizer="rmsprop",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"])

Before training, we’ll preprocess the data by reshaping it into the shape the model expects and scaling it so that all values are in the [0, 1] interval. Previously, our training images were stored in an array of shape (60000, 28, 28) of type uint8 with values in the [0, 255] interval. We’ll transform it into a float32 array of shape (60000, 28 * 28) with values between 0 and 1.

In [8]:
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype("float32") / 255
test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype("float32") / 255

In [9]:
model.fit(train_images, train_labels, epochs=5, batch_size=128)

Epoch 1/5
469/469 [==============================] - 3s 3ms/step - loss: 0.2645 - accuracy: 0.9240
Epoch 2/5
469/469 [==============================] - 1s 3ms/step - loss: 0.1078 - accuracy: 0.9686
Epoch 3/5
469/469 [==============================] - 1s 3ms/step - loss: 0.0705 - accuracy: 0.9793
Epoch 4/5
469/469 [==============================] - 1s 3ms/step - loss: 0.0509 - accuracy: 0.9847
Epoch 5/5
469/469 [==============================] - 1s 3ms/step - loss: 0.0388 - accuracy: 0.9887


In [10]:
test_digits = test_images[0:10]
predictions = model.predict(test_digits)
predictions[0]

1/1 [==============================] - 0s 66ms/step


array([4.1387318e-07, 3.8013162e-09, 8.5159909e-06, 8.0611295e-05,
       5.8251000e-12, 2.2399639e-07, 1.0475796e-11, 9.9990273e-01,
       7.4316972e-08, 7.4734244e-06], dtype=float32)

Each number of index i in that array corresponds to the probability that digit image
test_digits[0] belongs to class i.
 This first test digit has the highest probability score (0.99999106, almost 1) at
index 7, so according to our model, it must be a 7:

In [11]:
 predictions[0].argmax()

7

In [12]:
predictions[0][7]

0.9999027

In [18]:
predictions

array([[4.13873181e-07, 3.80131615e-09, 8.51599088e-06, 8.06112948e-05,
        5.82509995e-12, 2.23996395e-07, 1.04757956e-11, 9.99902725e-01,
        7.43169721e-08, 7.47342438e-06],
       [3.68125654e-08, 7.30353349e-05, 9.99915481e-01, 8.88692466e-06,
        2.15359360e-13, 2.90919928e-08, 6.60888801e-08, 3.08300564e-12,
        2.32629873e-06, 1.43907878e-12],
       [1.17545675e-07, 9.99246120e-01, 1.89473707e-04, 6.52058907e-06,
        6.85614068e-05, 5.31685146e-06, 5.87893464e-06, 2.37264438e-04,
        2.34263280e-04, 6.56124075e-06],
       [9.99970198e-01, 3.72092557e-09, 7.56569307e-06, 1.33332108e-07,
        8.12242806e-09, 1.68526071e-07, 3.73375678e-06, 2.82310424e-07,
        3.73550135e-10, 1.79274666e-05],
       [2.02757633e-07, 2.71677097e-10, 4.99753605e-06, 3.59674379e-09,
        9.99548376e-01, 8.77573836e-09, 6.77362891e-07, 1.08765717e-05,
        2.61641731e-07, 4.34538350e-04],
       [3.94139832e-09, 9.99599636e-01, 1.56802469e-06, 3.81455379e-07,
   

In [19]:
test_loss, test_acc = model.evaluate(test_images, test_labels)
print(f"test_acc: {test_acc}")

313/313 [==============================] - 1s 3ms/step - loss: 0.0631 - accuracy: 0.9793
test_acc: 0.9793000221252441
